kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: fc-sc
provisioner: filecache.csi.aws.com
parameters:
  subnetId: subnet-074ea3b7386e4802b
  securityGroupIds: sg-046ad64768e4cf756
  dataRepositoryAssociations: "FileCachePath=/ns1/,DataRepositoryPath=nfs://10.0.92.69/,NFS={Version=NFS3},DataRepositorySubdirectories=[subdir1,subdir2,subdir3]"
mountOptions:
  - flock
